condominio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('condominio_app.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),    name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),                  name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),   name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),                                                      name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),                                                                     name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),        name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

condominio_app/urls.py
from django.urls import path, register_converter
from django.conf import settings
from django.conf.urls.static import static

from datetime import date, datetime, timedelta
from . import views
from django.urls import path 
from .views import deudas_list 
from .views import generate_pdf
#from django.views.generic import RedirectView

# Template urls
app_name = 'condominio_app'

class DateConverter:
    regex = r'\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value

register_converter(DateConverter, 'yyyy')

urlpatterns = [
    
   
    #reporte de deudas
    
    path('recibo_total_deuda/<int:id>', views.recibo_total_deuda, name='r ecibo_total_deuda'),
    path('deudas_list/', views.deudas_list, name='deudas_list'),
    # Vistas de usuario
    path('', views.home, name='home'),
    #path('', RedirectView.as_view(url='home/', permanent=False)),
    path('check-static/', views.check_static, name='check_static'),
    path('check-settings/', views.check_settings, name='check_settings'),
    path('check-database/', views.check_database, name='check_database'),
    path('alquileres/', views.alquileresRedic, name='alquileres'),
    path('conf_reserva/', views.conf_reserva, name='conf_reserva'),
    path('update_view/<id_reservacion>', views.update_view, name='update_view'),
    path('editarEstado/', views.editarEstado, name='editarEstado'),
    path('domicilio_update/', views.domicilio_update, name='domicilio_update'),
    path('viviendas/', views.viviendas, name='viviendas'),
    path('local-comercial/', views.local_comercial, name='local_comercial'),
    path('alquiler-residencial/', views.alquiler_residencial, name='alquiler_residencial'),
    path('alquiler-vacacional/', views.alquiler_vacacional, name='alquiler_vacacional'),
    path('sobre-nosotros/', views.sobre_nosotros, name='sobre_nosotros'),
    path('cartelera-informativa/', views.cartelera_informativa, name='cartelera_informativa'),
    path('contacto/', views.contacto, name='contacto'),
    path('contacto/send_mail/', views.send_mail, name='send_mail'),
    path('cartelera-informativa/<slug>/', views.noticia, name="noticia"),
    path('reservacion/', views.reservacion, name="reservacion"),

    # Vistas de propietario
    path('home/propietarios/', views.home_propietarios, name='home_propietarios'),
    path('home/propietarios/pagos/', views.propietarios_pagos, name='propietarios_pagos'),
    path('home/propietarios/publicaciones/', views.propietarios_publicaciones, name='propietarios_publicaciones'),
    path('home/propietarios/recibos/', views.propietarios_recibos, name='propietarios_recibos'),
    path('home/propietarios/recibos/pdf/<int:id>', views.propietario_recibo_pago, name='propietario_recibo_pago'),

    # Vistas de administrador
    
    path('home/administrador/añadir_alquiler', views.añadir_alquiler, name='añadir_alquiler'),
    path('home/administrador/', views.home_admin, name='home_admin'),
    path('home/administrador/perfil/', views.admin_perfil, name="admin_perfil"),
    path('home/administrar/bancos/', views.admin_bancos, name="admin_bancos"),
    path('home/administrar/gastos/', views.admin_gastos, name="admin_gastos"),
    path('home/administrar/ingresos/', views.admin_ingresos, name="admin_ingresos"),
    path('home/administrar/deudas/', views.admin_deudas, name="admin_deudas"),
    path('home/administrar/deudas/abonar/<int:id>', views.admin_abono_deudas, name="admin_abono_deudas"),
    path('home/administrar/fondos/', views.admin_fondos, name="admin_fondos"),
    path('home/administrar/propietarios/', views.admin_propietarios, name="admin_propietarios"),
    path('home/administrar/propietarios/movimiento/', views.admin_propietarios_mov, name="admin_propietarios_mov"),
    path('home/administrar/validacion-pagos/', views.admin_validacion_pagos, name="admin_validacion_pagos"),
    path('home/administrar/torres/', views.admin_torres, name="admin_torres"),
    path('home/administrar/noticias/', views.admin_noticias, name="admin_noticias"),
    path('home/administrar/cuentas/', views.admin_cuentas, name="admin_cuentas"),
    path('home/administrar/reportes/', views.admin_reportes, name="admin_reportes"),
    path('home/administrar/cierres/', views.admin_cierres, name="admin_cierres"),
    path('home/administrar/configuracion/<str:type>', views.admin_configuracion, name="admin_configuracion"),
    path('home/administrar/configuracion/domicilios/', views.admin_domicilios, name="admin_domicilios"),
    path('home/administrar/reservacion/', views.reservacion, name='reservacion'),
    path('home/administrar/reservacion/<id_alquiler>/', views.reserva, name='reservacion'),
    
    #path('home/administrar/reservacion_list/', views.reservacion_list, name='reservacion_list'),

    # URLS de configuracion del edificio
    path('home/administrar/configuracion/recargos-y-descuentos/', views.configuracion_recargos_descuentos, name="configurar_recargos_y_descuentos"),
    path('home/administrar/configuracion/tasas-de-cambio/', views.configuracion_tasas_de_cambio, name="tasas_de_cambio"),
    path('home/administrar/configuracion/establecer-precios/', views.configuracion_establecimiento_precios, name="establecimiento_precios"),

    # READ
    path('home/administrar/bancos/ver/<int:id>', views.readBancos, name="readBancos"),
    path('home/administrar/gastos/ver/<int:id>', views.readGastos, name="readGastos"),
    path('home/administrar/ingresos/ver/<int:id>', views.readIngresos, name="readIngresos"),
    path('home/administrar/pagos/ver/<int:id>', views.readPagoMovimiento, name="readPagoMovimiento"),
    path('home/administrar/deudas/ver/<int:id>', views.readDeudas, name="readDeudas"),
    path('home/administrar/deudas/ver/propietario/<int:id>/<id_propietario>', views.readPropDeudas, name="readPropDeudas"),
    path('home/administrar/propietarios/ver/<int:id>', views.readPropietarios, name="readPropietarios"),
    path('home/administrar/cuentas/ver/<int:id>', views.readCuentas, name="readCuentas"),

    # UPDATE
    path('home/administrar/bancos/actualizar/<int:id>', views.updateBancos, name="updateBancos"),
    path('home/administrar/gastos/actualizar/<int:id>', views.updateGastos, name="updateGastos"),
    path('home/administrar/ingresos/actualizar/<int:id>', views.updateIngresos, name="updateIngresos"),
    path('home/administrar/deudas/actualizar/<int:pk>', views.DeudasUpdateView.as_view(), name="updateDeudas"),
    path('home/administrar/propietarios/actualizar/<int:id>', views.updatePropietarios, name="updatePropietarios"),
    path('home/administrar/cuentas/actualizar/<int:id>', views.updateCuentas, name="updateCuentas"),
    path('home/administrar/noticias/actualizar/<slug>', views.updateNoticia, name="updateNoticia"),
    path('home/administrar/torres/actualizar/<int:id>', views.updateTorres, name="updateTorres"),
    path('home/administrar/domicilio/actualizar/<id_domicilio>', views.updateDom, name="updateDom"),
    # path('home/administrar/domicilio/actualizar/<int:id>', views.updateDom, name="updateDom"),

    # DELETE
    path('home/administrar/bancos/eliminar/<int:id>', views.destroyBancos, name="destroyBancos"),
    path('home/administrar/gastos/eliminar/<int:id>', views.destroyGastos, name="destroyGastos"),
    path('home/administrar/ingresos/eliminar/<int:id>', views.destroyIngresos, name="destroyIngresos"),
    path('home/administrar/deudas/eliminar/<int:id>', views.destroyDeudas, name="destroyDeudas"),
    path('home/administrar/propietarios/eliminar/<int:id>', views.destroyPropietarios, name="destroyPropietarios"),
    path('home/administrar/cuentas/eliminar/<int:id>', views.destroyCuenta, name="destroyCuentas"),
    path('home/administrar/noticia/eliminar/<slug>', views.destroyNoticia, name="destroyNoticia"),
    path('home/administrar/torres/eliminar/<int:id>', views.destroyTorres, name="destroyTorres"),
    path('home/administrar/domicilio/eliminar/<int:id>', views.destroyDom, name="destroyDom"),

    #DOWNLOAD
    path('home/administrar/gastos/ver/referencia', views.downloadReferencia, name="downloadReferencia"),
    path('home/administrar/gastos/ver/referenciaI', views.downloadReferenciaingreso, name="downloadReferenciaingreso"),

    # UTILS
    path('home/administrar/propietarios/enviar_email/<int:id>', views.enviar_email, name="enviar_email"),
    path('obtener_pisos/', views.obtener_pisos, name='obtener_pisos'),
    path('obtener_bancos/', views.obtener_bancos, name='obtener_bancos'),
    path('admin_propietarios_mov/', views.admin_propietarios_mov, name='admin_propietarios_mov'),
    path('cierre_propietario/', views.cierre_propietario, name='cierre_propietario'),
    path('obtener_deudas/', views.obtener_deudas, name='obtener_deudas'),
    path('eliminar_publicacion/', views.eliminar_publicacion, name='eliminar_publicacion'),
    path('cambiar_monto/', views.cambiar_monto, name='cambiar_monto'),
    path('obtener_domicilio/', views.obtener_domicilio, name='obtener_domicilio'),
    path('enviar-consulta/', views.enviar_consulta, name="enviar_consulta"),
    path('cerrar-sesion/', views.cerrar_sesion, name="cerrar_sesion"),
    path('inicio/', views.redireccion_de_usuario, name="redireccion"),

    path('agregar_elemento/', views.agregar_elemento, name="agregar_elemento"),
    # path('eliminar_elemento/', views.eliminar_elemento, name="eliminar_elemento"),
    # path('eliminar_db/', views.limpiar_db, name="eliminar_todo"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/porteria/home_porteria.html
{% extends "layouts/admin-layout.html" %}

{% load static %}
{% load i18n %}

{% block title_page %}
Esparta Suites - Administración
{% endblock title_page %}

{% block modulo_label %}
<span class="" id="inicio-admin">Inicio</span>
{% endblock modulo_label %}

{% block opc_panel_class %}
class="col-lg-3 end-padding-left"
{% endblock opc_panel_class %}

{% block body_block %}
<!-- SECCIÓN DE INICIO -->
<div class="col-lg-12 mb-5 mb-lg-0 end-padding-right end-padding-left" id="InicioAdmin">
    <div class="container rounded modulo border border-secondary pb-2" style="background-color: #ffffff">
        <div class="container pt-3 pb-1">
            <h2 class="text-center pb-1">¡Bienvenido {{user}}!</h2>
            <div class="divider"></div>

            {% language 'es' %}
            {{weekend}}
            {% endlanguage %}

            <!-- INICIO -->
            <div class="mt-3">
                <div class="row pt-3">
                    <p class="normal-font text-dark col-sm-6">Correo Eléctronico: <span>{{usuario.email}}</span></p>
                    <p class="normal-font text-dark col-sm-6">Usuario: <span>{{usuario.username}}</span></p>
                </div>
                <div class="row pt-3">
                    <p class="normal-font text-dark col-sm-6">Estado de Cuenta:
                        {% if user.is_active == True %}
                        <span class="text-success">
                            Activo
                        </span>
                        {% else %}
                        <span class="text-danger">
                          Suspendido
                        </span>
                        {% endif %}
                    </p>
                </div>

                <div class="align-right object-right">
                    <a class="btn border btn-option-admin text-center align-right center-all" href="/password_change/">Cambiar
                        contraseña</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- FIN SECCIÓN DE INICIO -->
{% endblock body_block %}

templates/porteria/novedades_condominio.html
{% extends "layouts/admin-layout.html" %}

{% load static %}
{% load i18n %}

{% block title_page %}
  Esparta Suites - Administración
{% endblock title_page %}

{% block modulo_label %}
  <span class="" id="">Administración de Noticias</span>
{% endblock modulo_label %}

{% block opc_panel_class %}
  class="col-lg-3 end-padding-left"
{% endblock opc_panel_class %}

{% block options_admin %}
<ul class="sidebar-spacing">
    <li><a href="/home/administrador/" style="font-size: 12px !important;" class="a-sub-option">Inicio</a></li>
    <li class="active">
        <div class="dropdown d-lg-block">
            <a class="a-sub-option selected-option" style="font-size: 12px !important;" id="dropdownMenuLink" data-toggle="dropdown">
                Administrar <i class="fa fa-angle-down ml-2"></i>
            </a>
            <div class="dropdown-menu show-options" aria-labelledby="dropdownMenuLink">
                <a class="normal-font dropdown-item text-dark btn sub-option-menu"
                   href="/home/administrar/bancos/">Bancos</a>
                <a class="normal-font dropdown-item text-dark btn sub-option-menu"
                   href="/home/administrar/gastos/">Gastos</a>
                <a class="normal-font dropdown-item text-dark btn sub-option-menu"
                   href="/home/administrar/ingresos/">Ingresos</a>
                <a class="normal-font dropdown-item text-dark btn sub-option-menu"
                   href="/home/administrar/deudas/">Deudas</a>
                <a class="normal-font dropdown-item text-dark btn sub-option-menu"
                   href="/home/administrar/fondos/">Fondos</a>
                <a class="normal-font dropdown-item text-dark btn sub-option-menu"
                   href="/home/administrar/torres/">Torres</a>
                <a class="normal-font dropdown-item text-dark btn sub-option-menu"
                   href="/home/administrar/noticias/">Noticias</a>
                <a class="normal-font dropdown-item text-dark btn sub-option-menu"
                   href="/home/administrar/cuentas/">Administradores</a>
            </div>
        </div>
    </li>
    <li>
        <a href="/home/administrar/reportes/" style="font-size: 12px !important;" class="a-sub-option">
            Reportes
        </a>
    </li>
    <li>
        <a href="/home/administrar/validacion-pagos/" style="font-size: 12px !important;" class="a-sub-option">
            Validación de pagos
        </a>
    </li>
    <li>
        <a href="/home/administrar/cierres/" style="font-size: 12px !important;" class="a-sub-option">
            Cierre del Mes
        </a>
    </li>
    <li>
        <a href="{% url 'condominio_app:admin_configuracion' type='condominio' %}" style="font-size: 12px !important;" class="a-sub-option">
            Configuración
        </a>
    </li>
    <li>
        <a href="/home/administrar/propietarios/" style="font-size: 12px !important;" class="a-sub-option">
            Propietarios
        </a>
    </li>
</ul>
{% endblock options_admin %}

{% block body_block %}
<!-- INICIO GESTION DE NOTICIAS -->
<div class="col-lg-12 mb-5 mb-lg-0 end-padding-right end-padding-left" id="Lista-Noticias">
    <div class="container rounded modulo border border-secondary pb-2">
        <div class="container pt-3 pb-1">
            <h2 class="text-center pb-3">Noticias y Comunicados</h2>

            <div class="form-group row">
                <div class="col-sm-6 d-none" id="HideNoticia">
                    <button class="btn-size-text btn btn-danger ml-3 move-left" onclick="ShowOrHide('HideListaNoticias')"><i
                            class="fa fa-arrow-left pr-2"></i> Volver</button>
                </div>

                <button class="btn-option-admin mx-auto move-up" id="ShowNoticia" onclick="ShowOrHide('ShowListaNoticias')"
                        data-toggle="popover" data-content="Haz click aquí para ver la lista de noticias"><i
                        class="fa fa-list pr-2"></i> Lista de Noticias
                </button>
            </div>

            <div class="divider"></div>

            <!--AGREGAR NOTICIAS-->
            <form method="POST" id="AgregarNoticias" enctype="multipart/form-data">
              {% csrf_token %}
              <h3 class="text-center pt-2">Datos de la publicación</h3>
              <p class="text-center pb-2 text-dark">Haz un anuncio para que este sea visible en la cartelera informativa de la página.</p>

              <div class="form-group row">
                <label for="id_titulo" class="col-sm-2 col-form-label text-dark">Título:</label>
                <div class="col-sm-9">
                  <input type="text" class="form-control text-dark" id="id_titulo" name="titulo" required>
                </div>
              </div>

              <div class="form-group row">
                <label for="id_descripcion" class="col-sm-2 col-form-label text-dark">Descripción:</label>
                <div class="col-sm-9">
                  <textarea class="form-control text-dark" id="id_descripcion" name="descripcion" rows="10" required></textarea>
                </div>
              </div>

              <div class="form-group row">
                  <label for="id_imagen" class="col-sm-2 col-form-label text-dark">Imagen:</label>
                  <div class="col-sm-9">
                    <input type="file" class="custom-control-input" accept="image/*" name="imagen" id="id_imagen">
                    <label class="col-sm-12 custom-file-label" for="id_imagen">Suba la referencia aquí</label>
                  </div>
              </div>

                <button type="submit" class="btn btn-success col-sm-4 mt-3 move-up"><i class="fa fa-plus"></i> Publicar</button>
                <a href="/home/administrador/" class="btn btn-danger col-sm-2 mt-3 ml-3 move-up"><i class="fa fa-remove"></i> Cancelar</a>
            </form>

            <!--VER NOTICIAS-->
            <div class="d-none" id="VerNoticias">
                <br>
                <div class="input-div input-group">
                    <input type="text" class="form-control text-dark input-search" placeholder="Búsqueda Avanzada"
                           id="search_table">
                    <div class="input-group-append">
                        <span class="input-group-text icon-search"><img src="{% static '/img/search.png' %}"></span>
                    </div>
                </div>

                <table id="TablaNoticias"
                       class="table table-responsive-xl table-responsive-lg table-responsive-md table-hover"
                       width="100%">
                    <thead class="table-header-admin">
                    <tr>
                        <th scope="col" class="d-none">#</th>
                        <th scope="col">Titulo</th>
                        <th scope="col">Descripción</th>
                        <th scope="col">Fecha de publicación</th>
                        <th scope="col">Fecha de actualización</th>
                        <th scope="col">Acción</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% if noticias %}
                    {% for noticia in noticias %}
                    <tr>
                        <td scope="row" class="d-none">{{noticia.id}}</td>
                        <td class="centered-cell">{{noticia.titulo}}</td>
                        <td class="centered-cell">{{noticia.descripcion}}</td>
                        <td class="centered-cell">{{noticia.fecha_publicacion}}</td>
                        <td class="centered-cell">{{noticia.fecha_actualizado}}</td>
                        <td>
                            <div class="horizontal-cell">
                                <a href="{% url 'condominio_app:noticia' noticia.slug %}"
                                   class="btn btn-primary btn-option-admin border text-light button-table center-all"
                                   data-toggle="popover" data-content="Ver"><i class="fa fa-eye"></i></a>
                                <a href="{% url 'condominio_app:updateNoticia' noticia.slug %}"
                                   class="btn btn-primary btn-option-admin border text-light button-table center-all"
                                   data-toggle="popover" data-content="Editar"><i class="fa fa-pencil-square-o"></i></a>
                                <a href="{% url 'condominio_app:destroyNoticia' noticia.slug %}"
                                   class="btn btn-primary btn-option-admin border text-light button-table center-all"
                                   data-toggle="popover" data-content="Eliminar"><i class="fa fa-trash-o"></i></a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    {% endif %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function() {
        var table = $('#TablaNoticias').DataTable( {
          "processing": true,
          "language": {
            "lengthMenu": "Mostrar _MENU_ filas por página",
            "zeroRecords": "No se ha encontrado ningún dato",
            "info": "Página _PAGE_ de _PAGES_",
            "infoEmpty": "-",
            "infoFiltered": "(filtered from _MAX_ total records)",
            "loadingRecords": "Cargando...",
            "processing": "",
            "emptyTable": "No hay datos disponibles",
            "paginate": {
                "first":      "Primera",
                "last":       "Última",
                "next":       "Siguiente",
                "previous":   "Anterior"
            },
          },
          responsive: {
              details: false
          },
          autoWidth: false,
          columnDefs: [{
              targets: -1, // Última columna (0-indexed)
              width: '160px' // Cambia el valor '100px' según el ancho deseado
          }]
        });

        $('#search_table').on( 'keyup', function () {
            table.search( this.value ).draw();
        });
    });
</script>
  <!-- FIN DE GESTION DE NOTICIAS -->
{% endblock body_block %}