condominio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('condominio_app.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),    name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),                  name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),   name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),                                                      name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),                                                                     name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),        name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

condominio_app/urls.py
from django.urls import path, register_converter
from django.conf import settings
from django.conf.urls.static import static

from datetime import date, datetime, timedelta
from . import views
from django.urls import path 
from .views import deudas_list 
from .views import generate_pdf
#from django.views.generic import RedirectView

# Template urls
app_name = 'condominio_app'

class DateConverter:
    regex = r'\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value

register_converter(DateConverter, 'yyyy')

urlpatterns = [
    
   
    #reporte de deudas
    
    path('recibo_total_deuda/<int:id>', views.recibo_total_deuda, name='r ecibo_total_deuda'),
    path('deudas_list/', views.deudas_list, name='deudas_list'),
    # Vistas de usuario
    path('', views.home, name='home'),
    #path('', RedirectView.as_view(url='home/', permanent=False)),
    path('check-static/', views.check_static, name='check_static'),
    path('check-settings/', views.check_settings, name='check_settings'),
    path('check-database/', views.check_database, name='check_database'),
    path('alquileres/', views.alquileresRedic, name='alquileres'),
    path('conf_reserva/', views.conf_reserva, name='conf_reserva'),
    path('update_view/<id_reservacion>', views.update_view, name='update_view'),
    path('editarEstado/', views.editarEstado, name='editarEstado'),
    path('domicilio_update/', views.domicilio_update, name='domicilio_update'),
    path('viviendas/', views.viviendas, name='viviendas'),
    path('local-comercial/', views.local_comercial, name='local_comercial'),
    path('alquiler-residencial/', views.alquiler_residencial, name='alquiler_residencial'),
    path('alquiler-vacacional/', views.alquiler_vacacional, name='alquiler_vacacional'),
    path('sobre-nosotros/', views.sobre_nosotros, name='sobre_nosotros'),
    path('cartelera-informativa/', views.cartelera_informativa, name='cartelera_informativa'),
    path('contacto/', views.contacto, name='contacto'),
    path('contacto/send_mail/', views.send_mail, name='send_mail'),
    path('cartelera-informativa/<slug>/', views.noticia, name="noticia"),
    path('reservacion/', views.reservacion, name="reservacion"),

    # Vistas de propietario
    path('home/propietarios/', views.home_propietarios, name='home_propietarios'),
    path('home/propietarios/pagos/', views.propietarios_pagos, name='propietarios_pagos'),
    path('home/propietarios/publicaciones/', views.propietarios_publicaciones, name='propietarios_publicaciones'),
    path('home/propietarios/recibos/', views.propietarios_recibos, name='propietarios_recibos'),
    path('home/propietarios/recibos/pdf/<int:id>', views.propietario_recibo_pago, name='propietario_recibo_pago'),

    # Vistas de administrador
    
    path('home/administrador/añadir_alquiler', views.añadir_alquiler, name='añadir_alquiler'),
    path('home/administrador/', views.home_admin, name='home_admin'),
    path('home/administrador/perfil/', views.admin_perfil, name="admin_perfil"),
    path('home/administrar/bancos/', views.admin_bancos, name="admin_bancos"),
    path('home/administrar/gastos/', views.admin_gastos, name="admin_gastos"),
    path('home/administrar/ingresos/', views.admin_ingresos, name="admin_ingresos"),
    path('home/administrar/deudas/', views.admin_deudas, name="admin_deudas"),
    path('home/administrar/deudas/abonar/<int:id>', views.admin_abono_deudas, name="admin_abono_deudas"),
    path('home/administrar/fondos/', views.admin_fondos, name="admin_fondos"),
    path('home/administrar/propietarios/', views.admin_propietarios, name="admin_propietarios"),
    path('home/administrar/propietarios/movimiento/', views.admin_propietarios_mov, name="admin_propietarios_mov"),
    path('home/administrar/validacion-pagos/', views.admin_validacion_pagos, name="admin_validacion_pagos"),
    path('home/administrar/torres/', views.admin_torres, name="admin_torres"),
    path('home/administrar/noticias/', views.admin_noticias, name="admin_noticias"),
    path('home/administrar/cuentas/', views.admin_cuentas, name="admin_cuentas"),
    path('home/administrar/reportes/', views.admin_reportes, name="admin_reportes"),
    path('home/administrar/cierres/', views.admin_cierres, name="admin_cierres"),
    path('home/administrar/configuracion/<str:type>', views.admin_configuracion, name="admin_configuracion"),
    path('home/administrar/configuracion/domicilios/', views.admin_domicilios, name="admin_domicilios"),
    path('home/administrar/reservacion/', views.reservacion, name='reservacion'),
    path('home/administrar/reservacion/<id_alquiler>/', views.reserva, name='reservacion'),
    
    #path('home/administrar/reservacion_list/', views.reservacion_list, name='reservacion_list'),

    # URLS de configuracion del edificio
    path('home/administrar/configuracion/recargos-y-descuentos/', views.configuracion_recargos_descuentos, name="configurar_recargos_y_descuentos"),
    path('home/administrar/configuracion/tasas-de-cambio/', views.configuracion_tasas_de_cambio, name="tasas_de_cambio"),
    path('home/administrar/configuracion/establecer-precios/', views.configuracion_establecimiento_precios, name="establecimiento_precios"),

    # READ
    path('home/administrar/bancos/ver/<int:id>', views.readBancos, name="readBancos"),
    path('home/administrar/gastos/ver/<int:id>', views.readGastos, name="readGastos"),
    path('home/administrar/ingresos/ver/<int:id>', views.readIngresos, name="readIngresos"),
    path('home/administrar/pagos/ver/<int:id>', views.readPagoMovimiento, name="readPagoMovimiento"),
    path('home/administrar/deudas/ver/<int:id>', views.readDeudas, name="readDeudas"),
    path('home/administrar/deudas/ver/propietario/<int:id>/<id_propietario>', views.readPropDeudas, name="readPropDeudas"),
    path('home/administrar/propietarios/ver/<int:id>', views.readPropietarios, name="readPropietarios"),
    path('home/administrar/cuentas/ver/<int:id>', views.readCuentas, name="readCuentas"),

    # UPDATE
    path('home/administrar/bancos/actualizar/<int:id>', views.updateBancos, name="updateBancos"),
    path('home/administrar/gastos/actualizar/<int:id>', views.updateGastos, name="updateGastos"),
    path('home/administrar/ingresos/actualizar/<int:id>', views.updateIngresos, name="updateIngresos"),
    path('home/administrar/deudas/actualizar/<int:pk>', views.DeudasUpdateView.as_view(), name="updateDeudas"),
    path('home/administrar/propietarios/actualizar/<int:id>', views.updatePropietarios, name="updatePropietarios"),
    path('home/administrar/cuentas/actualizar/<int:id>', views.updateCuentas, name="updateCuentas"),
    path('home/administrar/noticias/actualizar/<slug>', views.updateNoticia, name="updateNoticia"),
    path('home/administrar/torres/actualizar/<int:id>', views.updateTorres, name="updateTorres"),
    path('home/administrar/domicilio/actualizar/<id_domicilio>', views.updateDom, name="updateDom"),
    # path('home/administrar/domicilio/actualizar/<int:id>', views.updateDom, name="updateDom"),

    # DELETE
    path('home/administrar/bancos/eliminar/<int:id>', views.destroyBancos, name="destroyBancos"),
    path('home/administrar/gastos/eliminar/<int:id>', views.destroyGastos, name="destroyGastos"),
    path('home/administrar/ingresos/eliminar/<int:id>', views.destroyIngresos, name="destroyIngresos"),
    path('home/administrar/deudas/eliminar/<int:id>', views.destroyDeudas, name="destroyDeudas"),
    path('home/administrar/propietarios/eliminar/<int:id>', views.destroyPropietarios, name="destroyPropietarios"),
    path('home/administrar/cuentas/eliminar/<int:id>', views.destroyCuenta, name="destroyCuentas"),
    path('home/administrar/noticia/eliminar/<slug>', views.destroyNoticia, name="destroyNoticia"),
    path('home/administrar/torres/eliminar/<int:id>', views.destroyTorres, name="destroyTorres"),
    path('home/administrar/domicilio/eliminar/<int:id>', views.destroyDom, name="destroyDom"),

    #DOWNLOAD
    path('home/administrar/gastos/ver/referencia', views.downloadReferencia, name="downloadReferencia"),
    path('home/administrar/gastos/ver/referenciaI', views.downloadReferenciaingreso, name="downloadReferenciaingreso"),

    # UTILS
    path('home/administrar/propietarios/enviar_email/<int:id>', views.enviar_email, name="enviar_email"),
    path('obtener_pisos/', views.obtener_pisos, name='obtener_pisos'),
    path('obtener_bancos/', views.obtener_bancos, name='obtener_bancos'),
    path('admin_propietarios_mov/', views.admin_propietarios_mov, name='admin_propietarios_mov'),
    path('cierre_propietario/', views.cierre_propietario, name='cierre_propietario'),
    path('obtener_deudas/', views.obtener_deudas, name='obtener_deudas'),
    path('eliminar_publicacion/', views.eliminar_publicacion, name='eliminar_publicacion'),
    path('cambiar_monto/', views.cambiar_monto, name='cambiar_monto'),
    path('obtener_domicilio/', views.obtener_domicilio, name='obtener_domicilio'),
    path('enviar-consulta/', views.enviar_consulta, name="enviar_consulta"),
    path('cerrar-sesion/', views.cerrar_sesion, name="cerrar_sesion"),
    path('inicio/', views.redireccion_de_usuario, name="redireccion"),

    path('agregar_elemento/', views.agregar_elemento, name="agregar_elemento"),
    # path('eliminar_elemento/', views.eliminar_elemento, name="eliminar_elemento"),
    # path('eliminar_db/', views.limpiar_db, name="eliminar_todo"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/visitante/about.html
{% extends "layouts/base-layout.html" %}

{% load static %}
{% load i18n %}

{% block title_page %}
  Esparta Suites - Sobre Nosotros
{% endblock title_page %}

{% block informacion_active %}
	class="active"
{% endblock informacion_active %}

{% block body_block %}

  <!-- bradcam_area_start -->
  <div class="bradcam_area breadcam_bg">
    <h3>Sobre nosotros</h3>
  </div>
  <!-- bradcam_area_end -->
  
  <!-- about_area_start -->
	<div class="about_area">
		<div class="container">
			<div class="row">
				<div class="col-xl-5 col-lg-5">
					<div class="about_info">
						<div class="section_title mb-20px">
							<span>Sobre nosotros</span>
							<h3>Ciudad Chinita</h3>
						</div>
						<p>Encuentra todo lo que buscas en el CC. Ciudad Chinita, ubicado en el casco central de maracaibo, frente a la antigua panorama</p>
						<a href="#info" class="line-button">Learn More</a>
					</div>
				</div>
				<div class="col-xl-7 col-lg-7">
					<div class="about_thumb d-flex">
						<div class="img_1">
							<img src="{% static '/img/about/about_1.png' %}" alt="">
						</div>
						<div class="img_2">
							<img src="{% static '/img/about/about_2.png' %}" alt="">
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- about_area_end -->

	<!-- about_info_area_start -->
	<div class="about_info_area">
		<div class="about_active owl-carousel">
			<div class="single_slider about_bg_1"></div>
			<div class="single_slider about_bg_1"></div>
			<div class="single_slider about_bg_1"></div>
			<div class="single_slider about_bg_1"></div>
		</div>
	</div>
	<!-- about_info_area_start -->

	<!-- about_main_info_start -->
	<div class="about_main_info" id="info">
		<div class="container">
			<div class="row">
				<div class="col-xl-6 col-md-6">
					<div class="single_about_info">
						<h3>[Descripción 1]</h3>
						<p>Suscipit libero pretium nullam potenti. Interdum, blandit phasellus consectetuer dolor ornare
							dapibus enim ut tincidunt  rhoncus tellus sollicitudin pede nam maecenas, dolor sem.  Neque
							sollicitudin enim. Dapibus lorem feugiat facilisi  faucibus et. Rhoncus.
						</p>
					</div>
				</div>
				<div class="col-xl-6 col-md-6">
					<div class="single_about_info">
						<h3>[Descripción 2]</h3>
						<p>Suscipit libero pretium nullam potenti. Interdum, blandit <br> phasellus consectetuer dolor ornare
							dapibus enim ut tincidunt <br> rhoncus tellus sollicitudin pede nam maecenas, dolor sem. <br> Neque
							sollicitudin enim. Dapibus lorem feugiat facilisi <br> faucibus et. Rhoncus.
						</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- about_main_info_end -->

	<!-- forQuery_start -->
	<div class="forQuery">
		<div class="container">
			<div class="row">
				<div class="col-xl-12 offset-xl-0 col-md-12">
					<div class="Query_border">
						<div class="row align-items-center justify-content-center">
							<div class="col-xl-5 col-md-6">
								<div class="Query_text">
									<p>¿Tienes alguna duda? Contactanos!</p>
								</div>
							</div>
							<div class="col-xl-7 col-md-6">
								<div class="phone_num">
									<a href="#" class="mobile_no">+58 295-2629586</a>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- forQuery_end-->
{% endblock body_block %}

templates/visitante/alquiler_vacacional.html
{% extends "layouts/base-layout.html" %}

{% load static %}
{% load i18n %}

{% block title_page %}
  Esparta Suites - Apartamentos
{% endblock title_page %}

{% block aptos_active %}
	class="active"
{% endblock aptos_active %}

{% block body_block %}
<!-- bradcam_area_start -->
<div class="bradcam_area breadcam_bg_1">
	<h3>Viviendas Vacacionales</h3>
	<h4 class="mt-3 white">¿Buscas una vivienda para desconectarte por unos dias? Entonces no te pierdas las ofertas!</h4>
</div>
<!-- bradcam_area_end -->

{% if pagina_actual %}

<!-- SECCIÓN DE APARTAMENTOS EN ALQUILER O EN VENTA -->
<div class="offers_area padding_top">
	<div class="container">
		<div class="row">
			<div class="col-xl-12">
				<div class="section_title text-center mb-100">
					<h3>Para Alquiler Vacacional</h3>
					<h4>Ofrecemos diferentes tipos de domicilios que se ajusten a lo que buscas</h4>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- FIN SECCIÓN DE APTOS EN ALQUILER O EN VENTA -->

<!-- SECCIÓN PT 2 DE APTOS EN ALQUILER O EN VENTA (Para simular un catalogo de 6 aptos para mostrar nada más en la página principal) -->
<div class="offers_area">
	<div class="container">
		<div class="row">
			{% for item in pagina_actual %}
			<div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
				<div class="single_offers">
					<div class="about_thumb">
						<img src="{{ item.imagen.url }}" width="120px" height="250px" alt="imagen_post">
					</div>
					<h3>{{item.titulo}}</h3>
					<ul>
						<li>Tamaño: 601 m²</li>
						<li>Habitaciones: 5</li>
						<li>Baños: 6</li>
						<li>Estacionamientos: 4</li>
					</ul>
					<button class="book_now mostrarContacto" data-item="{{ item.value }}">Contactar al propietario</button>
				</div>
				<div class="showPopup" id="showPopup">
					<div class="popup alinear-lista" id="popup">
						<h3 class="line-title">Datos de Contacto</h3>
						<ul>
							<div id="data_prop"></div>
							<li>Nombre: {{item.id_domicilio.id_propietario.nombre_propietario}}</li>
							<li>Contacto: {{item.contacto}}</li>
							<li>Descripcion: {{item.descripcion}}</li>
							<br>
							<li>Horario de consulta desde {{item.horario_desde}} hasta las {{item.horario_hasta}}</li>
							<br>
						</ul>

						<button class="btn-popup" id="cerrarContacto">Cerrar</button>
					</div>
				</div>
				<br>
			</div>
			{% endfor %}
		</div>

		<!-- Mostrar los enlaces de paginación -->
		<div class="pagination blog-pagination d-flex">
				<span class="step-links">

					{% if pagina_actual.has_previous %}
						<a href="?pagina=1" class="pagination-action">&laquo; Primera</a>
						<a href="?pagina={{ pagina_actual.previous_page_number }}"
						   class="pagination-action">Anterior</a>
					{% endif %}

					{% for num in pagina_actual.paginator.page_range %}
						{% if pagina_actual.number == num %}
							<span class="pagination-number pagination-current">{{ num }}</span>
						{% elif num > pagina_actual.number|add:'-3' and num < pagina_actual.number|add:'3' %}
							<a class="pagination-number" href="?pagina={{ num }}">{{ num }}</a>
						{% endif %}
					{% endfor %}

					{% if pagina_actual.has_next %}
						<a href="?pagina={{ pagina_actual.next_page_number }}" class="pagination-action">Siguiente</a>
						<a href="?pagina={{ pagina_actual.paginator.num_pages }}" class="pagination-action">&Uacute;ltima &raquo;</a>
					{% endif %}
				</span>
		</div>
	</div>
</div>
<!-- FIN SECCION PT 2 APTOS EN ALQUILER O EN VENTA -->

{% else %}
<div class="forQuery padding_top_100">
	<div class="container Query_border">
		<div class="row">
			<div class="col-xl-12">
				<div class="not-exists-title text-center">
					<h3>Ahora mismo, el condominio no cuenta con viviendas vacacionales disponibles</h3>
				</div>
			</div>
		</div>
	</div>
</div>
{% endif %}

<!-- forQuery_start -->
<div class="forQuery">
	<div class="container">
		<div class="row">
			<div class="col-xl-12 offset-xl-0 col-md-12">
				<div class="Query_border">
					<div class="row align-items-center justify-content-center">
						<div class="col-xl-5 col-md-6">
							<div class="Query_text">
								<p>¿Necesitas hacer una consulta?</p><br>
								<p class="justify-content-center">¡Contactanos!</p>
							</div>
						</div>
						<div class="col-xl-7 col-md-6">
							<div class="phone_num">
								<a class="mobile_no">+58 295-2629586</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script src="{% static '/js/main.js' %}"></script>
<script src="{% static '/js/scripts.js' %}"></script>
	<!-- forQuery_end-->
{% endblock body_block %}

templates/visitante/cartelera.html
{% extends "layouts/base-layout.html" %}

{% load static %}
{% load i18n %}

{% block title_page %}
  Esparta Suites - Inicio
{% endblock title_page %}

{% block informacion_active %}
	class="active"
{% endblock informacion_active %}

{% block body_block %}
  <!-- bradcam_area_start -->
	<div class="bradcam_area breadcam_bg">
		<h3>Cartelera Informativa</h3>
	</div>
	<!-- bradcam_area_end -->


	<!--================Blog Area =================-->
	<section class="blog_area section-padding">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 mb-5 mb-lg-0">
					<div class="blog_left_sidebar">
						{% if noticias %}
							{% for noticia in noticias %}
								{% include 'snippets/noticias_snippet.html' with noticias=noticia %}
							{% endfor %}
						{% else %}
							<div class="blog-post-container">
								{% include 'snippets/noticias_snippet.html' with query=query %}
							</div>
						{% endif %}
						
						{% include 'snippets/pagination_snippet.html' with noticias=noticias %}
					
					</div>
				</div>

				<div class="col-lg-4">
					<div class="blog_right_sidebar">
						<aside class="single_sidebar_widget search_widget">
							<form method="GET">
								<div class="form-group">
									<div class="input-group mb-3">
										<input type="text" class="form-control" placeholder='Palabras clave' onfocus="this.placeholder = ''"
											onblur="this.placeholder = 'Palabras clave'" name="q" id="id_q">
										<div class="input-group-append">
											<button class="btn" type="button"><i class="ti-search"></i></button>
										</div>
									</div>
								</div>
								<button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
									type="submit">Buscar</button>
							</form>
						</aside>

						<aside class="single_sidebar_widget popular_post_widget">
							<h3 class="widget_title">Publicaciones recientes</h3>
              {% if recent_posts %}
                {% for recent_post in recent_posts|slice:4 %}
                  <div class="media post_item">
                    <img src="{{recent_post.imagen.url}}" alt="post" width="80px" height="80px">
                    <div class="media-body">
                      <a href="{% url 'condominio_app:noticia' recent_post.slug %}">
                        <h3>{{recent_post.titulo}}</h3>
                      </a>
                      <p><i class="fa fa-calendar"></i> Publicado el {{recent_post.fecha_publicacion|date:"d/m/Y"}}</p>
                    </div>
                  </div>
                {% endfor %}
              {% endif %}
						</aside>

						<aside class="single_sidebar_widget instagram_feeds">
							<h4 class="widget_title">Publicaciones de Instagram</h4>
							<ul class="instagram_row flex-wrap">
								<li>
									<a href="#">
										<img class="img-fluid" src="{% static '/img/post/post_5.png' %}" alt="">
									</a>
								</li>
								<li>
									<a href="#">
										<img class="img-fluid" src="{% static '/img/post/post_6.png' %}" alt="">
									</a>
								</li>
								<li>
									<a href="#">
										<img class="img-fluid" src="{% static '/img/post/post_7.png' %}" alt="">
									</a>
								</li>
								<li>
									<a href="#">
										<img class="img-fluid" src="{% static '/img/post/post_8.png' %}" alt="">
									</a>
								</li>
								<li>
									<a href="#">
										<img class="img-fluid" src="{% static '/img/post/post_9.png' %}" alt="">
									</a>
								</li>
								<li>
									<a href="#">
										<img class="img-fluid" src="{% static '/img/post/post_10.png' %}" alt="">
									</a>
								</li>
							</ul>
						</aside>
					</div>
				</div>
				
			</div>
		</div>
	</section>
	<!--================Blog Area =================-->
{% endblock body_block %}

templates/visitante/contacto.html
{% extends "layouts/base-layout.html" %}

{% load static %}
{% load i18n %}

{% block title_page %}
  Esparta Suites - Contacto
{% endblock title_page %}

{% block contacto_active %}
	class="active"
{% endblock contacto_active %}

{% block body_block %}
<!-- bradcam_area_start -->
<div class="bradcam_area breadcam_bg_2">
	<h3>Contacto</h3>
</div>
<!-- bradcam_area_end -->

<!-- ================ contact section start ================= -->
<section class="contact-section">
	<div class="container">
		<div class="d-none d-sm-block mb-5 pb-4">
			<div id="map" style="height: 480px; position: relative; overflow: hidden;">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3916.889299667705!2d-63.82261054905718!3d10.971727692150793!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c318ee10db7993d%3A0x566bf812fd9dda8c!2sEsparta%20Suites!5e0!3m2!1ses!2sve!4v1619141356218!5m2!1ses!2sve"
						width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
			</div>
		</div>


		<div class="row">
			<div class="col-12">
				<h2 class="contact-title">Contacta con nosotros</h2>
			</div>
			<div class="col-lg-8">

				<form class="form-contact contact_form" method="POST" action="{% url 'condominio_app:send_mail' %}">
					{% csrf_token %}
					<div class="row">
						<div class="col-12">
							<div class="form-group">
									<textarea class="form-control w-100" name="body" id="body" cols="30" rows="9"
											  onfocus="this.placeholder = ''"
											  onblur="this.placeholder = 'Escribe tu mensaje...'"
											  placeholder="Escribe tu mensaje..."></textarea>
							</div>
						</div>

						<div class="col-sm-6">
							<div class="form-group">
								<input class="form-control valid" name="nombre" id="nombre" type="text"
									   onfocus="this.placeholder = ''"
									   onblur="this.placeholder = 'Escribe tu Nombre completo'"
									   placeholder="Nombre completo">
							</div>
						</div>

						<div class="col-sm-6">
							<div class="form-group">
								<input class="form-control valid" name="email" id="email" type="email"
									   onfocus="this.placeholder = ''"
									   onblur="this.placeholder = 'Escribe tu correo eléctronico'"
									   placeholder="Correo Eléctronico">
							</div>
						</div>

						<div class="col-12">
							<div class="form-group">
								<input class="form-control" name="asunto" id="asunto" type="text"
									   onfocus="this.placeholder = ''"
									   onblur="this.placeholder = 'Escribe el asunto de tu mensaje'"
									   placeholder="Asunto">
							</div>
						</div>

						<div class="form-group mt-3">
							<button type="submit" class="button button-contactForm boxed-btn">Enviar consulta</button>
						</div>
					</div>
				</form>
				<img src="https://i.postimg.cc/j2LwJpxF/preguntas.jpg" alt="" style="border-radius: 40%;">
			</div>
			<div class="col-lg-3 offset-lg-1">
				<div class="media contact-info">
					<span class="contact-info__icon"><i class="ti-home"></i></span>
					<div class="media-body">
						<h3>Nueva Esparta, Venezuela.</h3>
						<p>Porlamar, VE 6301</p>
					</div>
				</div>
				<div class="media contact-info">
					<span class="contact-info__icon"><i class="ti-tablet"></i></span>
					<div class="media-body">
						<h3>+58 295-2629586</h3>
						<p>Lunes a Viernes 8am a 4pm</p>
					</div>
				</div>
				<div class="media contact-info">
					<span class="contact-info__icon"><i class="ti-email"></i></span>
					<div class="media-body">
						<h3>inverdata@gmail.com</h3>
						<p>¡Envianos tu consulta en cualquier momento!</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- ================ contact section end ================= -->
{% endblock body_block %}