condominio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('condominio_app.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),    name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),                  name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),   name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),                                                      name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),                                                                     name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),        name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

condominio_app/urls.py
from django.urls import path, register_converter
from django.conf import settings
from django.conf.urls.static import static

from datetime import date, datetime, timedelta
from . import views
from django.urls import path 
from .views import deudas_list 
from .views import generate_pdf
#from django.views.generic import RedirectView

# Template urls
app_name = 'condominio_app'

class DateConverter:
    regex = r'\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value

register_converter(DateConverter, 'yyyy')

urlpatterns = [
    
   
    #reporte de deudas
    
    path('recibo_total_deuda/<int:id>', views.recibo_total_deuda, name='r ecibo_total_deuda'),
    path('deudas_list/', views.deudas_list, name='deudas_list'),
    # Vistas de usuario
    path('', views.home, name='home'),
    #path('', RedirectView.as_view(url='home/', permanent=False)),
    path('check-static/', views.check_static, name='check_static'),
    path('check-settings/', views.check_settings, name='check_settings'),
    path('check-database/', views.check_database, name='check_database'),
    path('alquileres/', views.alquileresRedic, name='alquileres'),
    path('conf_reserva/', views.conf_reserva, name='conf_reserva'),
    path('update_view/<id_reservacion>', views.update_view, name='update_view'),
    path('editarEstado/', views.editarEstado, name='editarEstado'),
    path('domicilio_update/', views.domicilio_update, name='domicilio_update'),
    path('viviendas/', views.viviendas, name='viviendas'),
    path('local-comercial/', views.local_comercial, name='local_comercial'),
    path('alquiler-residencial/', views.alquiler_residencial, name='alquiler_residencial'),
    path('alquiler-vacacional/', views.alquiler_vacacional, name='alquiler_vacacional'),
    path('sobre-nosotros/', views.sobre_nosotros, name='sobre_nosotros'),
    path('cartelera-informativa/', views.cartelera_informativa, name='cartelera_informativa'),
    path('contacto/', views.contacto, name='contacto'),
    path('contacto/send_mail/', views.send_mail, name='send_mail'),
    path('cartelera-informativa/<slug>/', views.noticia, name="noticia"),
    path('reservacion/', views.reservacion, name="reservacion"),

    # Vistas de propietario
    path('home/propietarios/', views.home_propietarios, name='home_propietarios'),
    path('home/propietarios/pagos/', views.propietarios_pagos, name='propietarios_pagos'),
    path('home/propietarios/publicaciones/', views.propietarios_publicaciones, name='propietarios_publicaciones'),
    path('home/propietarios/recibos/', views.propietarios_recibos, name='propietarios_recibos'),
    path('home/propietarios/recibos/pdf/<int:id>', views.propietario_recibo_pago, name='propietario_recibo_pago'),

    # Vistas de administrador
    
    path('home/administrador/añadir_alquiler', views.añadir_alquiler, name='añadir_alquiler'),
    path('home/administrador/', views.home_admin, name='home_admin'),
    path('home/administrador/perfil/', views.admin_perfil, name="admin_perfil"),
    path('home/administrar/bancos/', views.admin_bancos, name="admin_bancos"),
    path('home/administrar/gastos/', views.admin_gastos, name="admin_gastos"),
    path('home/administrar/ingresos/', views.admin_ingresos, name="admin_ingresos"),
    path('home/administrar/deudas/', views.admin_deudas, name="admin_deudas"),
    path('home/administrar/deudas/abonar/<int:id>', views.admin_abono_deudas, name="admin_abono_deudas"),
    path('home/administrar/fondos/', views.admin_fondos, name="admin_fondos"),
    path('home/administrar/propietarios/', views.admin_propietarios, name="admin_propietarios"),
    path('home/administrar/propietarios/movimiento/', views.admin_propietarios_mov, name="admin_propietarios_mov"),
    path('home/administrar/validacion-pagos/', views.admin_validacion_pagos, name="admin_validacion_pagos"),
    path('home/administrar/torres/', views.admin_torres, name="admin_torres"),
    path('home/administrar/noticias/', views.admin_noticias, name="admin_noticias"),
    path('home/administrar/cuentas/', views.admin_cuentas, name="admin_cuentas"),
    path('home/administrar/reportes/', views.admin_reportes, name="admin_reportes"),
    path('home/administrar/cierres/', views.admin_cierres, name="admin_cierres"),
    path('home/administrar/configuracion/<str:type>', views.admin_configuracion, name="admin_configuracion"),
    path('home/administrar/configuracion/domicilios/', views.admin_domicilios, name="admin_domicilios"),
    path('home/administrar/reservacion/', views.reservacion, name='reservacion'),
    path('home/administrar/reservacion/<id_alquiler>/', views.reserva, name='reservacion'),
    
    #path('home/administrar/reservacion_list/', views.reservacion_list, name='reservacion_list'),

    # URLS de configuracion del edificio
    path('home/administrar/configuracion/recargos-y-descuentos/', views.configuracion_recargos_descuentos, name="configurar_recargos_y_descuentos"),
    path('home/administrar/configuracion/tasas-de-cambio/', views.configuracion_tasas_de_cambio, name="tasas_de_cambio"),
    path('home/administrar/configuracion/establecer-precios/', views.configuracion_establecimiento_precios, name="establecimiento_precios"),

    # READ
    path('home/administrar/bancos/ver/<int:id>', views.readBancos, name="readBancos"),
    path('home/administrar/gastos/ver/<int:id>', views.readGastos, name="readGastos"),
    path('home/administrar/ingresos/ver/<int:id>', views.readIngresos, name="readIngresos"),
    path('home/administrar/pagos/ver/<int:id>', views.readPagoMovimiento, name="readPagoMovimiento"),
    path('home/administrar/deudas/ver/<int:id>', views.readDeudas, name="readDeudas"),
    path('home/administrar/deudas/ver/propietario/<int:id>/<id_propietario>', views.readPropDeudas, name="readPropDeudas"),
    path('home/administrar/propietarios/ver/<int:id>', views.readPropietarios, name="readPropietarios"),
    path('home/administrar/cuentas/ver/<int:id>', views.readCuentas, name="readCuentas"),

    # UPDATE
    path('home/administrar/bancos/actualizar/<int:id>', views.updateBancos, name="updateBancos"),
    path('home/administrar/gastos/actualizar/<int:id>', views.updateGastos, name="updateGastos"),
    path('home/administrar/ingresos/actualizar/<int:id>', views.updateIngresos, name="updateIngresos"),
    path('home/administrar/deudas/actualizar/<int:pk>', views.DeudasUpdateView.as_view(), name="updateDeudas"),
    path('home/administrar/propietarios/actualizar/<int:id>', views.updatePropietarios, name="updatePropietarios"),
    path('home/administrar/cuentas/actualizar/<int:id>', views.updateCuentas, name="updateCuentas"),
    path('home/administrar/noticias/actualizar/<slug>', views.updateNoticia, name="updateNoticia"),
    path('home/administrar/torres/actualizar/<int:id>', views.updateTorres, name="updateTorres"),
    path('home/administrar/domicilio/actualizar/<id_domicilio>', views.updateDom, name="updateDom"),
    # path('home/administrar/domicilio/actualizar/<int:id>', views.updateDom, name="updateDom"),

    # DELETE
    path('home/administrar/bancos/eliminar/<int:id>', views.destroyBancos, name="destroyBancos"),
    path('home/administrar/gastos/eliminar/<int:id>', views.destroyGastos, name="destroyGastos"),
    path('home/administrar/ingresos/eliminar/<int:id>', views.destroyIngresos, name="destroyIngresos"),
    path('home/administrar/deudas/eliminar/<int:id>', views.destroyDeudas, name="destroyDeudas"),
    path('home/administrar/propietarios/eliminar/<int:id>', views.destroyPropietarios, name="destroyPropietarios"),
    path('home/administrar/cuentas/eliminar/<int:id>', views.destroyCuenta, name="destroyCuentas"),
    path('home/administrar/noticia/eliminar/<slug>', views.destroyNoticia, name="destroyNoticia"),
    path('home/administrar/torres/eliminar/<int:id>', views.destroyTorres, name="destroyTorres"),
    path('home/administrar/domicilio/eliminar/<int:id>', views.destroyDom, name="destroyDom"),

    #DOWNLOAD
    path('home/administrar/gastos/ver/referencia', views.downloadReferencia, name="downloadReferencia"),
    path('home/administrar/gastos/ver/referenciaI', views.downloadReferenciaingreso, name="downloadReferenciaingreso"),

    # UTILS
    path('home/administrar/propietarios/enviar_email/<int:id>', views.enviar_email, name="enviar_email"),
    path('obtener_pisos/', views.obtener_pisos, name='obtener_pisos'),
    path('obtener_bancos/', views.obtener_bancos, name='obtener_bancos'),
    path('admin_propietarios_mov/', views.admin_propietarios_mov, name='admin_propietarios_mov'),
    path('cierre_propietario/', views.cierre_propietario, name='cierre_propietario'),
    path('obtener_deudas/', views.obtener_deudas, name='obtener_deudas'),
    path('eliminar_publicacion/', views.eliminar_publicacion, name='eliminar_publicacion'),
    path('cambiar_monto/', views.cambiar_monto, name='cambiar_monto'),
    path('obtener_domicilio/', views.obtener_domicilio, name='obtener_domicilio'),
    path('enviar-consulta/', views.enviar_consulta, name="enviar_consulta"),
    path('cerrar-sesion/', views.cerrar_sesion, name="cerrar_sesion"),
    path('inicio/', views.redireccion_de_usuario, name="redireccion"),

    path('agregar_elemento/', views.agregar_elemento, name="agregar_elemento"),
    # path('eliminar_elemento/', views.eliminar_elemento, name="eliminar_elemento"),
    # path('eliminar_db/', views.limpiar_db, name="eliminar_todo"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/administrador/update/bancos_update.html
{% extends "layouts/admin-layout.html" %}

{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block title_page %}
  Esparta Suites - Administración
{% endblock title_page %}

{% block modulo_label %}
  <span class="" id="gestionar-bancos">Actualizar Banco</span>
{% endblock modulo_label %}

{% block opc_panel_class %}
  class="col-lg-3 end-padding-left"
{% endblock opc_panel_class %}

{% block body_block %}
  <!-- INICIO MAESTRO DE BANCOS -->
  <div class="col-lg-12 mb-5 mb-lg-0 end-padding-right end-padding-left" id="Bancos">
    <div class="container rounded modulo border-secondary pb-2">
      <div class="container pt-3 pb-1">

        <div class="divider"></div>

        <!-- FORMULARIO PARA AGREGAR NUEVAS MENSUALIDADES -->
        <form id="AgregarBancos" class="" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group row">
            <label for="{{ bancos_form.nombre_titular.name }}" class="col-sm-3 col-form-label text-dark">{{ bancos_form.nombre_titular.label }}:</label>
            <div class="col-sm-8">
              {% render_field bancos_form.nombre_titular class="form-control text-dark" placeholder="Ingrese el nombre del titular de la cuenta bancaria" value=bancos.nombre_titular %}
              {% for error in bancos_form.nombre_titular.errors %}
                <div class="alert alert-danger mt-2">{{ error }}</div>
              {% endfor %}
            </div>
          </div>
          <div class="form-group row">
            <label for="{{ bancos_form.dni_titular.name }}" class="col-sm-3 col-form-label text-dark">{{ bancos_form.dni_titular.label }}:</label>
            <div class="col-sm-2">
              <select name="{{ bancos_form.tipo_dni_titular.name }}" id="{{ bancos_form.tipo_dni_titular.name }}" class="form-control text-dark">
                {% for select in bancos_form.tipo_dni_titular  %}
                  {{select}}
                  {% for error in bancos_form.tipo_dni_titular.errors %}
                    <div class="alert alert-danger mt-2">{{ error }}</div>
                  {% endfor %}
                {% endfor %}
                
              </select>
            </div>
            <div class="col-sm-6">
              {% render_field bancos_form.dni_titular class="form-control text-dark" name=bancos_form.dni_titular.name placeholder="Ingrese el número de identificación del titular" value=bancos.dni_titular %}
              {% for error in bancos_form.dni_titular.errors %}
                <div class="alert alert-danger mt-2">{{ error }}</div>
              {% endfor %}
            </div>
          </div>

          <div class="form-group row">
            <label for="{{ bancos_form.nro_cuenta.name }}" class="col-sm-3 col-form-label text-dark">{{ bancos_form.nro_cuenta.label }}:</label>
            <div class="col-sm-8">
              {% render_field bancos_form.nro_cuenta class="form-control text-dark" placeholder="Ingrese el número de cuenta del banco" name=bancos_form.nro_cuenta.name  maxlength="24" value=bancos.nro_cuenta %}
              {% for error in bancos_form.nro_cuenta.errors %}
                <div class="alert alert-danger mt-2">{{ error }}</div>
              {% endfor %}
            </div>
          </div>
          
            <div class="form-group row">
              <label for="{{ bancos_form.email_titular.name }}" class="col-sm-3 col-form-label text-dark">{{ bancos_form.email_titular.label }}:</label>
              <div class="col-sm-8">
                {% render_field bancos_form.email_titular class="form-control text-dark" placeholder="Ingrese el correo electrónico del titular" name=bancos_form.email_titular.name value=bancos.email_titular %}
                {% for error in bancos_form.email_titular.errors %}
                  <div class="alert alert-danger mt-2">{{ error }}</div>
                {% endfor %}
              </div>
            </div>

            <div class="form-group row">
              <label for="{{ bancos_form.tlf_titular.name }}" class="col-sm-3 col-form-label text-dark">{{ bancos_form.tlf_titular.label }}:</label>

              <div class="col-sm-2">
                <select name="{{ cod_tlf.cod_tlf.name }}" id="{{ cod_tlf.cod_tlf.name }}" class="form-control text-dark">
                  {% for select in cod_tlf.cod_tlf  %}
                    {{select}}
                    {% for error in cod_tlf.cod_tlf.errors %}
                      <div class="alert alert-danger mt-2">{{ error }}</div>
                    {% endfor %}
                  {% endfor %}
                  
                </select>
              </div>

              <div class="col-sm-6">
                {% render_field bancos_form.tlf_titular type='number' class="form-control text-dark" placeholder="Ingrese el número de teléfono del titular" name=bancos_form.tlf_titular value=tlf %}
                {% for error in bancos_form.tlf_titular.errors %}
                  <div class="alert alert-danger mt-2">{{ error }}</div>
                {% endfor %}
              </div>
            </div>

            <button type="submit" class="btn btn-success col-sm-4 mt-3 move-up"><i class="fa fa-plus"></i> Actualizar Banco</button>

            <a type="reset" class="btn btn-danger col-sm-2 mt-3 ml-3 move-up"
               href="/home/administrar/configuracion/condominio?tab=bancos&lista=1"><i class="fa fa-remove"></i> Cancelar</a>
        </form>

      </div>
    </div>
  </div>
  <!-- FIN MAESTRO DE BANCOS -->
{% endblock body_block %}

templates/administrador/update/cuentas_update.html
{% extends "layouts/admin-layout.html" %}

{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block title_page %}
  Esparta Suites - Administración
{% endblock title_page %}

{% block modulo_label %}
  <span class="" id="gestionar-usuarios">Actualización de Cuenta</span>
{% endblock modulo_label %}

{% block opc_panel_class %}
  class="col-lg-3 end-padding-left"
{% endblock opc_panel_class %}

{% block body_block %}
<!-- INICIO GESTION DE USUARIOS -->
<div class="col-lg-12 mb-5 mb-lg-0 end-padding-right end-padding-left" id="Cuentas">
  <div class="container rounded modulo border border-secondary pb-2">
    <div class="container pt-3 pb-1">
      <h2 class="text-center pb-3">Actualizar Usuario</h2>

      <div class="row" >
        
      </div>
      <div class="form-group row">
        <div class="col-sm-4 d-none" id="HideUsuarios">
          <a class="btn btn-danger ml-3 move-left" href="/home/administrar/cuentas"><i class="fa fa-arrow-left pr-2"></i> Volver</a>
        </div>

      </div>

      <div class="divider"></div>

      <!-- FORMULARIO PARA AGREGAR NUEVAS MENSUALIDADES -->
      <form id="AgregarUsuarios" method="POST" class="mt-4">
        {% csrf_token %}

        <div class="form-group row">
          <label for="username" class="col-sm-3 col-form-label text-dark">Nombre completo:</label>
          <div class="col-sm-6">
            <input type="text" class="form-control text-dark" id="nombre_propietario" name="nombre_propietario" required placeholder="Nombre del administrador" required value={{propietarios.nombre_propietario}}>
          </div>
        </div>

        <div class="form-group row">
          <label for="status" class="col-sm-3 col-form-label text-dark">Identificación:</label>
          <div class="col-sm-3">
            <select class="form-control text-dark" id="tipo_dni" name="tipo_dni">
              <option value="V">Venezolano</option>
              <option value="J">Juridico</option>
              <option value="E">Extranjero</option>
              <option value="P">Pasaporte</option>
            </select>
          </div>
          <div class="col-sm-3">
            <input type="number" name="dni" id="dni" class="form-control text-dark" placeholder="Identificación" required value={{propietarios.dni}}>
          </div>
        </div>

        <div class="form-group row">
          <label for="email" class="col-sm-3 col-form-label text-dark">Correo electrónico:</label>
          <div class="col-sm-6">
            <input type="email" name="email" id="email" class="form-control text-dark" placeholder="Ingrese el correo electrónico del propietario" required value={{usuarios.email}}>
            {% for error in user_form.email.errors %}
              <div class="alert alert-danger mt-2">{{ error }}</div>
            {% endfor %}
          </div>
        </div>

        <div class="form-group row">
          <label for="username" class="col-sm-3 col-form-label text-dark">Nombre de usuario:</label>
          <div class="col-sm-6">
            <input type="text" name="username" id="username" class="form-control text-dark" placeholder="Ingrese el nombre de usuario" required value={{usuarios.username}}>
            {% for error in user_form.username.errors %}
              <div class="alert alert-danger mt-2">{{ error }}</div>
            {% endfor %}
          </div>
        </div>

        <button type="submit" class="btn btn-success col-sm-4 mt-3 move-up"><i class="fa fa-save pr-2"></i> Actualizar el usuario</button>
        <a class="btn btn-danger col-sm-2 mt-3 ml-3 move-up" href="/home/administrar/cuentas"><i class="fa fa-times pr-2"></i> Cancelar</a>
      </form>

    </div>
  </div>
</div>
<!-- FIN DE GESTION DE USUARIOS -->
{% endblock body_block %}

templates/administrador/update/deudas_update.html
{% extends "layouts/admin-layout.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% load widget_tweaks %}

{% block title_page %}
  Esparta Suites - Administración
{% endblock title_page %}

{% block modulo_label %}
  <span class="" id="gestionar-deudas">Actualizar Deuda</span>
{% endblock modulo_label %}

{% block opc_panel_class %}
  class="col-lg-3 end-padding-left"
{% endblock opc_panel_class %}

{% block body_block %}
  <!-- INICIO MAESTRO DE INGRESOS -->
  <div class="col-lg-12 mb-5 mb-lg-0 end-padding-right end-padding-left" id="Deudas">
    <div class="container rounded modulo border-secondary pb-2">
      <div class="container pt-3 pb-1">
        {% if deuda_condo %}
        <h2 class="text-center pb-3">Deuda del condominio</h2>
        {% else %}
        <h2 class="text-center pb-3">Deuda del propietario</h2>
        {% endif %}

        <div class="divider"></div>

        <!-- FORMULARIO -->
          {% csrf_token %}
          {% crispy form %}
      </div>
    </div>
  </div>
  <!-- FIN MAESTRO DE INGRESOS -->
{% endblock body_block %}

templates/administrador/update/domicilio_update.html
{% extends "layouts/admin-layout.html" %}


{% load static %}
{% load i18n %}
{% load widget_tweaks %}
{% block modulo_label %}
<span>Actualizacion de datos:</span>
{% endblock modulo_label %}
{% block body_block %}

<form action="/domicilio_update/" method="POST">
    {% csrf_token %}
    <div class="form-style-10 col-sm-12 mt-3" style="
    width: 42rem;
    display: grid;
    margin-left: 10rem;">
   
    <div class="form-group">
        <div class="inner-wrap form-row" bis_skin_checked="1" style="
    display: block;">
        <label for="Codigo Domicilio">Codigo del domicilio</label>
        <input type="text" name="txtCodigo" id="txtCodigo" value="{{domicilio.id_domicilio}}" class="form-control" readonly> <!--cambiar opacidad-->
    </div>
    </div>
    <div class="section mb-3"><span>1</span>Ubicación del inmueble</div>
    <div class="inner-wrap form-row" bis_skin_checked="1" style="
    display: block;">
    <div class="form-group">
        <label for="Nombre de la torre">Torre</label>
        <input type="text" name="txtTorre" id="txtTorre" value="{{domicilio.id_torre.nombre_torre}}"class="form-control" readonly> <!--cambiar opacidad-->
        </div>
    <div class="form-group">
        <label for="Piso">Piso</label>
        <input type="text" name="txtPisos" id="txtPisos" value="{{domicilio.id_torre.pisos}}"class="form-control" required> <!--cambiar opacidad-->
    </div>
    </div>  
    <div class="inner-wrap form-row" bis_skin_checked="1" style="
    display: block;">
    <div class="section mb-3"><span>2</span>Informacion del inmueble</div>
    <div class="form-group">
        <label for="Nombre del domicilio">Nombre del domicilio</label>
        <input type="text" id="txtNombreDomicilio" name="txtNombreDomicilio" value="{{domicilio.nombre_domicilio}}" class="form-control col-12 col-sm-6 col-md-6 col-lg-4">
    </div>
    <div class="form-group">
        <label for="">Tipo de domicilio</label>
        <select name="txtTipoDomicilio" id="txtTipoDomicilio" class="select_torre form-control text-dark"  required >
            <option value="" selected="" disabled="">Seleccione... </option>
            <option value="Apartamento">Apartamento</option> <!--cambiar opacidad-->
            <option value="Casa">Casa</option><!--cambiar opacidad-->
            <option value="Terreno">Terreno</option><!--cambiar opacidad-->
            <option value="Edificio">Edificio</option><!--cambiar opacidad-->
          </select>

     </div>
     <div class="form-group">
        <label for="Nombre del domicilio">Tamaño del inmueble (m²): </label>
        <input type="text" id="txtZiseDomicilio" name="txtZiseDomicilio" value="{{domicilio.size_domicilio}}" class="form-control col-12 col-sm-6 col-md-6 col-lg-4"><!--cambiar opacidad-->
     </div>
     <div class="form-group">
        <label for="Nombre del domicilio">Numero de estacionamientos</label>
        <input type="text" id="txtEstacionamientos" name="txtEstacionamientos" value="{{domicilio.estacionamientos}}" class="form-control col-12 col-sm-6 col-md-6 col-lg-4"><!--cambiar opacidad-->
    </div>
    </div>

    <div class="section mb-3"><span>3</span>Informacion del Propietario</div>
    <div class="inner-wrap form-row" bis_skin_checked="1" style="display: block;">
    <div class="size col-sm-12">
        <label for="Nombre del propietario">Nombre del propietario</label>
        <input type="text" id="txtNombrePropietario" name="txtNombrePropietario" value="{{domicilio.id_propietario.nombre_propietario}}" class="form-control text-dark"><!--cambiar opacidad--> 
        <br>
        <label for="C.I del propietario">C.I del propietario</label>
        <input type="text" id="" name="" value="{{domicilio.id_propietario.dni}}" class="form-control text-dark" readonly><!--cambiar opacidad--> 
        <br>
        <small class="mb-2 form-text text-center text-muted">Para modificar los campos relacionados con el propietariohaga clic aqui: <a style="color:#974608;"href="{% url 'condominio_app:admin_propietarios' %}" class="mb-2 form-text text-center text-muted"> <strong>Propietarios</strong></a></small>
        <br>
        <button type="submit" value="Actualizar" class="btn btn-success btn-block text-white" style="width: 75%;margin-top: 4rem;">Actualizar</button>
        <a class="btn btn-danger col-sm-12 border text-light move-up btn-cancel mt-3"
           href="/home/administrar/configuracion/condominio?tab=domicilios&lista=1"><i class="fa fa-arrow-left float-left pt-1"></i> Volver</a>
    </div>
    </div>
    </div>


</form>



    

{% endblock %}