condominio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('condominio_app.urls')),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'),    name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'),                  name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),   name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),                                                      name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(),                                                                     name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),        name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

condominio_app/urls.py
from django.urls import path, register_converter
from django.conf import settings
from django.conf.urls.static import static

from datetime import date, datetime, timedelta
from . import views
from django.urls import path 
from .views import deudas_list 
from .views import generate_pdf
#from django.views.generic import RedirectView

# Template urls
app_name = 'condominio_app'

class DateConverter:
    regex = r'\d{4}-\d{2}-\d{2}'

    def to_python(self, value):
        return datetime.strptime(value, '%Y-%m-%d')

    def to_url(self, value):
        return value

register_converter(DateConverter, 'yyyy')

urlpatterns = [
    
   
    #reporte de deudas
    
    path('recibo_total_deuda/<int:id>', views.recibo_total_deuda, name='r ecibo_total_deuda'),
    path('deudas_list/', views.deudas_list, name='deudas_list'),
    # Vistas de usuario
    path('', views.home, name='home'),
    #path('', RedirectView.as_view(url='home/', permanent=False)),
    path('check-static/', views.check_static, name='check_static'),
    path('check-settings/', views.check_settings, name='check_settings'),
    path('check-database/', views.check_database, name='check_database'),
    path('alquileres/', views.alquileresRedic, name='alquileres'),
    path('conf_reserva/', views.conf_reserva, name='conf_reserva'),
    path('update_view/<id_reservacion>', views.update_view, name='update_view'),
    path('editarEstado/', views.editarEstado, name='editarEstado'),
    path('domicilio_update/', views.domicilio_update, name='domicilio_update'),
    path('viviendas/', views.viviendas, name='viviendas'),
    path('local-comercial/', views.local_comercial, name='local_comercial'),
    path('alquiler-residencial/', views.alquiler_residencial, name='alquiler_residencial'),
    path('alquiler-vacacional/', views.alquiler_vacacional, name='alquiler_vacacional'),
    path('sobre-nosotros/', views.sobre_nosotros, name='sobre_nosotros'),
    path('cartelera-informativa/', views.cartelera_informativa, name='cartelera_informativa'),
    path('contacto/', views.contacto, name='contacto'),
    path('contacto/send_mail/', views.send_mail, name='send_mail'),
    path('cartelera-informativa/<slug>/', views.noticia, name="noticia"),
    path('reservacion/', views.reservacion, name="reservacion"),

    # Vistas de propietario
    path('home/propietarios/', views.home_propietarios, name='home_propietarios'),
    path('home/propietarios/pagos/', views.propietarios_pagos, name='propietarios_pagos'),
    path('home/propietarios/publicaciones/', views.propietarios_publicaciones, name='propietarios_publicaciones'),
    path('home/propietarios/recibos/', views.propietarios_recibos, name='propietarios_recibos'),
    path('home/propietarios/recibos/pdf/<int:id>', views.propietario_recibo_pago, name='propietario_recibo_pago'),

    # Vistas de administrador
    
    path('home/administrador/añadir_alquiler', views.añadir_alquiler, name='añadir_alquiler'),
    path('home/administrador/', views.home_admin, name='home_admin'),
    path('home/administrador/perfil/', views.admin_perfil, name="admin_perfil"),
    path('home/administrar/bancos/', views.admin_bancos, name="admin_bancos"),
    path('home/administrar/gastos/', views.admin_gastos, name="admin_gastos"),
    path('home/administrar/ingresos/', views.admin_ingresos, name="admin_ingresos"),
    path('home/administrar/deudas/', views.admin_deudas, name="admin_deudas"),
    path('home/administrar/deudas/abonar/<int:id>', views.admin_abono_deudas, name="admin_abono_deudas"),
    path('home/administrar/fondos/', views.admin_fondos, name="admin_fondos"),
    path('home/administrar/propietarios/', views.admin_propietarios, name="admin_propietarios"),
    path('home/administrar/propietarios/movimiento/', views.admin_propietarios_mov, name="admin_propietarios_mov"),
    path('home/administrar/validacion-pagos/', views.admin_validacion_pagos, name="admin_validacion_pagos"),
    path('home/administrar/torres/', views.admin_torres, name="admin_torres"),
    path('home/administrar/noticias/', views.admin_noticias, name="admin_noticias"),
    path('home/administrar/cuentas/', views.admin_cuentas, name="admin_cuentas"),
    path('home/administrar/reportes/', views.admin_reportes, name="admin_reportes"),
    path('home/administrar/cierres/', views.admin_cierres, name="admin_cierres"),
    path('home/administrar/configuracion/<str:type>', views.admin_configuracion, name="admin_configuracion"),
    path('home/administrar/configuracion/domicilios/', views.admin_domicilios, name="admin_domicilios"),
    path('home/administrar/reservacion/', views.reservacion, name='reservacion'),
    path('home/administrar/reservacion/<id_alquiler>/', views.reserva, name='reservacion'),
    
    #path('home/administrar/reservacion_list/', views.reservacion_list, name='reservacion_list'),

    # URLS de configuracion del edificio
    path('home/administrar/configuracion/recargos-y-descuentos/', views.configuracion_recargos_descuentos, name="configurar_recargos_y_descuentos"),
    path('home/administrar/configuracion/tasas-de-cambio/', views.configuracion_tasas_de_cambio, name="tasas_de_cambio"),
    path('home/administrar/configuracion/establecer-precios/', views.configuracion_establecimiento_precios, name="establecimiento_precios"),

    # READ
    path('home/administrar/bancos/ver/<int:id>', views.readBancos, name="readBancos"),
    path('home/administrar/gastos/ver/<int:id>', views.readGastos, name="readGastos"),
    path('home/administrar/ingresos/ver/<int:id>', views.readIngresos, name="readIngresos"),
    path('home/administrar/pagos/ver/<int:id>', views.readPagoMovimiento, name="readPagoMovimiento"),
    path('home/administrar/deudas/ver/<int:id>', views.readDeudas, name="readDeudas"),
    path('home/administrar/deudas/ver/propietario/<int:id>/<id_propietario>', views.readPropDeudas, name="readPropDeudas"),
    path('home/administrar/propietarios/ver/<int:id>', views.readPropietarios, name="readPropietarios"),
    path('home/administrar/cuentas/ver/<int:id>', views.readCuentas, name="readCuentas"),

    # UPDATE
    path('home/administrar/bancos/actualizar/<int:id>', views.updateBancos, name="updateBancos"),
    path('home/administrar/gastos/actualizar/<int:id>', views.updateGastos, name="updateGastos"),
    path('home/administrar/ingresos/actualizar/<int:id>', views.updateIngresos, name="updateIngresos"),
    path('home/administrar/deudas/actualizar/<int:pk>', views.DeudasUpdateView.as_view(), name="updateDeudas"),
    path('home/administrar/propietarios/actualizar/<int:id>', views.updatePropietarios, name="updatePropietarios"),
    path('home/administrar/cuentas/actualizar/<int:id>', views.updateCuentas, name="updateCuentas"),
    path('home/administrar/noticias/actualizar/<slug>', views.updateNoticia, name="updateNoticia"),
    path('home/administrar/torres/actualizar/<int:id>', views.updateTorres, name="updateTorres"),
    path('home/administrar/domicilio/actualizar/<id_domicilio>', views.updateDom, name="updateDom"),
    # path('home/administrar/domicilio/actualizar/<int:id>', views.updateDom, name="updateDom"),

    # DELETE
    path('home/administrar/bancos/eliminar/<int:id>', views.destroyBancos, name="destroyBancos"),
    path('home/administrar/gastos/eliminar/<int:id>', views.destroyGastos, name="destroyGastos"),
    path('home/administrar/ingresos/eliminar/<int:id>', views.destroyIngresos, name="destroyIngresos"),
    path('home/administrar/deudas/eliminar/<int:id>', views.destroyDeudas, name="destroyDeudas"),
    path('home/administrar/propietarios/eliminar/<int:id>', views.destroyPropietarios, name="destroyPropietarios"),
    path('home/administrar/cuentas/eliminar/<int:id>', views.destroyCuenta, name="destroyCuentas"),
    path('home/administrar/noticia/eliminar/<slug>', views.destroyNoticia, name="destroyNoticia"),
    path('home/administrar/torres/eliminar/<int:id>', views.destroyTorres, name="destroyTorres"),
    path('home/administrar/domicilio/eliminar/<int:id>', views.destroyDom, name="destroyDom"),

    #DOWNLOAD
    path('home/administrar/gastos/ver/referencia', views.downloadReferencia, name="downloadReferencia"),
    path('home/administrar/gastos/ver/referenciaI', views.downloadReferenciaingreso, name="downloadReferenciaingreso"),

    # UTILS
    path('home/administrar/propietarios/enviar_email/<int:id>', views.enviar_email, name="enviar_email"),
    path('obtener_pisos/', views.obtener_pisos, name='obtener_pisos'),
    path('obtener_bancos/', views.obtener_bancos, name='obtener_bancos'),
    path('admin_propietarios_mov/', views.admin_propietarios_mov, name='admin_propietarios_mov'),
    path('cierre_propietario/', views.cierre_propietario, name='cierre_propietario'),
    path('obtener_deudas/', views.obtener_deudas, name='obtener_deudas'),
    path('eliminar_publicacion/', views.eliminar_publicacion, name='eliminar_publicacion'),
    path('cambiar_monto/', views.cambiar_monto, name='cambiar_monto'),
    path('obtener_domicilio/', views.obtener_domicilio, name='obtener_domicilio'),
    path('enviar-consulta/', views.enviar_consulta, name="enviar_consulta"),
    path('cerrar-sesion/', views.cerrar_sesion, name="cerrar_sesion"),
    path('inicio/', views.redireccion_de_usuario, name="redireccion"),

    path('agregar_elemento/', views.agregar_elemento, name="agregar_elemento"),
    # path('eliminar_elemento/', views.eliminar_elemento, name="eliminar_elemento"),
    # path('eliminar_db/', views.limpiar_db, name="eliminar_todo"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/administrador/read/deudas_read.html
{% extends "layouts/admin-layout.html" %}

{% load static %}
{% load i18n %}

{% block title_page %}
  Esparta Suites - Administración
{% endblock title_page %}


{% block modulo_label %}
{% for deuda in deudas %}
  <span class="">Deuda | {{deuda.concepto_deuda}}</span>
{% endfor %}
{% endblock modulo_label %}


{% block opc_panel_class %}
  class="col-lg-3 end-padding-left"
{% endblock opc_panel_class %}

{% block body_block %}
<div class="col-lg-12 mb-5 mb-lg-0 end-padding-right end-padding-left" id="Bancos">
  <div class="container rounded modulo border-secondary pb-2">
    <div class="container pt-3 pb-1">

      <div class="divider"></div>

      {% if deudas %}
      {% for deuda in deudas %}
      <div class="row pt-3">
      </div>
          <div class="row pt-3">
            <p class="normal-font text-dark col-sm-6"><strong>Concepto de la deuda:</strong> <span>{{deuda.concepto_deuda}}</span></p>
            <p class="normal-font text-dark col-sm-6"><strong>Descripción de la deuda:</strong> <span>{{deuda.descripcion_deuda}}</span></p>
          </div>
          <div class="row pt-3">
            <p class="normal-font text-dark col-sm-6"><strong>Fecha de la deuda:</strong> <span>{{deuda.fecha_deuda}}</span></p>
            <p class="normal-font text-dark col-sm-6"><strong>Monto de la deuda:</strong> <span class="text-success">{{deuda.monto_deuda}}</span></p>
          </div>
          <div class="row pt-3">
              {% if deuda.is_active %}
              <p class="normal-font text-dark col-sm-12"><strong>Estado de la deuda:</strong> <span>Activa</span></p>
              {% else %}
              <p class="normal-font text-dark col-sm-12 text-center"><strong>Estado de la deuda:<span class="text-success"> Liquidada</span></strong></p>
              {% endif %}
          </div>
      {% endfor %}
          <div class="d-grid pt-3" style="justify-content: right;">
            <a class="btn btn-danger btn-cancel col-sm-12 border text-light move-up"
              href="{{ back_url|default:'/home/administrar/deudas/' }}"><i class="fa fa-arrow-left float-left pt-1"></i> Volver al inicio</a>
          </div>
      {% endif %}
          
    </div>
  </div>
</div>
{% endblock body_block %}

templates/administrador/read/gastos_read.html
{% extends "layouts/admin-layout.html" %}

{% load static %}
{% load i18n %}

{% block title_page %}
Esparta Suites - Administración
{% endblock title_page %}

{% block modulo_label %}
<span class="">Ver Gasto</span>
{% endblock modulo_label %}

{% block opc_panel_class %}
class="col-lg-3 end-padding-left"
{% endblock opc_panel_class %}

{% block body_block %}
<div class="col-lg-12 mb-5 mb-lg-0 end-padding-right end-padding-left" id="Bancos">
    <div class="container rounded modulo border-secondary pb-2">
        <div class="container pt-3 pb-1">

            <div class="divider"></div>

            {% if gastos %}
            <div class="row pt-1">
                <p class="normal-font text-dark col-sm-6"><strong>Concepto del gasto:</strong> <span>{{gastos.id_movimiento.concepto_movimiento}}</span>
                </p>
                <p class="normal-font text-dark col-sm-6"><strong>Descripción del gasto:</strong> <span>{{gastos.id_movimiento.descripcion_movimiento}}</span>
                </p>
            </div>
            <div class="row pt-1">
                <p class="normal-font text-dark col-sm-6"><strong>Fecha en la que se realizó el gasto:</strong> <span>{{gastos.id_movimiento.fecha_movimiento|date:"l, d/m/Y"}}</span>
                </p>
                <p class="normal-font text-dark col-sm-6"><strong>Monto del gasto:</strong> <span class="text-danger">{{gastos.id_movimiento.monto_movimiento}}</span>
                </p>
            </div>
            <div class="row pt-1">
                <p class="normal-font text-dark col-sm-6"><strong>Tipo de gasto:</strong>
                    <span>{{gastos.tipo_gasto}}</span></p>
                <p class="normal-font text-dark col-sm-6"><strong>Banco al que se le hizo el debito del gasto:</strong>
                    <span>{{gastos.id_movimiento.id_banco.nombre_banco}}</span></p>
            </div>
            <div class="row pt-1">
                <p class="normal-font text-dark col-sm-6"><strong>Fecha de registro del gasto:</strong> <span class="">{{gastos.id_movimiento.created_at|date:"l, d/m/Y"}}</span>
                </p>
                <p class="normal-font text-dark col-sm-6"><strong>Última actualización:</strong> <span class="">{{gastos.id_movimiento.created_at|date:"l, d/m/Y"}}</span>
                </p>
            </div>
            <div class="dropdown-divider"></div>
            {% if gastos.imagen_referencial %}
            <div class="row center-area">
                <form method="POST" id="Confirm_form" class="center-area" action="{% url 'condominio_app:downloadReferencia' %}">
                    {% csrf_token %}
                    <input type="text" value="{{gastos.id_gasto}}" name="id_gasto" hidden="hidden">
                    <input type="text" value="{{gastos.imagen_referencial}}" name="ruta_imagen" hidden="hidden">
                    <button type="submit" style="font-size: 13px;" class="btn center-area btn-info mx-auto move-up"><strong>Descargar referencia</strong></button>
                </form>
            </div>
            {% else %}
            <div class="row pt-1">
                <p class="normal-font text-center text-dark col-sm-12 text-center"><strong>No se subió imagen de referencia</strong></p>
            </div>
            {% endif %}
            <div class="dropdown-divider"></div>
            <div class="d-grid pt-3" style="justify-content: right;">
                <a class="btn btn-danger btn-cancel col-sm-12 border text-light move-up"
                   href="{{ back_url|default:'/home/administrar/gastos' }}"><i class="fa fa-arrow-left float-left pt-1"></i> Volver al inicio</a>
            </div>

            {% else %}

            {% endif %}


        </div>
    </div>
</div>
{% endblock body_block %}

templates/administrador/read/ingresos_read.html
{% extends "layouts/admin-layout.html" %}

{% load static %}
{% load i18n %}

{% block title_page %}
  Esparta Suites - Administración
{% endblock title_page %}

{% block modulo_label %}
  <span class="">Ver Ingreso</span>
{% endblock modulo_label %}

{% block opc_panel_class %}
  class="col-lg-3 end-padding-left"
{% endblock opc_panel_class %}

{% block body_block %}
<div class="col-lg-12 mb-5 mb-lg-0 end-padding-right end-padding-left" id="Bancos">
  <div class="container rounded modulo border-secondary pb-2">
    <div class="container pt-3 pb-1">

      <div class="divider"></div>

      {% if ingresos %}
      <div class="row pt-3">
        <!-- <p class="normal-font text-dark col-sm-12 text-center"><strong>Nombre del banco:</strong><br>
          <span>{{bancos.nombre_banco}}</span>
        </p> -->
      </div>
          <div class="row pt-3">
            <p class="normal-font text-dark col-sm-6"><strong>Concepto del ingreso:</strong> <span>{{ingresos.id_movimiento.concepto_movimiento}}</span></p>
            <p class="normal-font text-dark col-sm-6"><strong>Descripción del ingreso:</strong> <span>{{ingresos.id_movimiento.descripcion_movimiento}}</span></p>
          </div>
          <div class="row pt-3">
            <p class="normal-font text-dark col-sm-6"><strong>Fecha en la que se realizó el ingreso:</strong> <span>{{ingresos.id_movimiento.fecha_movimiento|date:"l, d/m/Y"}}</span></p>
            <p class="normal-font text-dark col-sm-6"><strong>Monto del ingreso:</strong> <span class="text-success">{{ingresos.id_movimiento.monto_movimiento}}</span></p>
          </div>
          <div class="row pt-3">
            <p class="normal-font text-dark col-sm-6"><strong>Fecha de registro del ingreso:</strong> <span class="">{{ingresos.id_movimiento.created_at|date:"l, d/m/Y"}}</span></p>
            <p class="normal-font text-dark col-sm-6"><strong>Última actualización:</strong> <span class="">{{ingresos.id_movimiento.created_at|date:"l, d/m/Y"}}</span></p>
          </div>
          <div class="row pt-3">
            {% if propietario %}
            {% for prop in propietario %}
              <p class="normal-font text-dark col-sm-6"><strong>Apartamento que realizó el ingreso:</strong> <span>{{prop.nombre_propietario}}</span></p>
            {% endfor %}
            {% endif %}
            <p class="normal-font text-dark col-sm-6"><strong>Banco que recibio el ingreso:</strong> <span>{{ingresos.id_movimiento.id_banco.nombre_banco}}</span></p>
          </div>
          {% if ingresos.imagen_referencial %}
            <div class="row center-area">
                <form method="POST" id="Confirm_form" class="center-area" action="{% url 'condominio_app:downloadReferenciaingreso' %}">
                    {% csrf_token %}
                    <input type="text" value="{{ingresos.id_ingreso}}" name="id_ingreso" hidden="hidden">
                    <input type="text" value="{{ingresos.imagen_referencial}}" name="ruta_imagen" hidden="hidden">
                    <button type="submit" style="font-size: 13px;" class="btn center-area btn-info mx-auto move-up"><strong>Descargar referencia</strong></button>
                </form>
            </div>
            {% else %}
            <div class="row pt-1">
                <p class="normal-font text-center text-dark col-sm-12 text-center"><strong>No se subió imagen de referencia</strong></p>
            </div>
            {% endif %}
          <div class="dropdown-divider"></div>
          <div class="d-grid pt-3" style="justify-content: right;">
            <a class="btn btn-danger btn-cancel col-sm-12 border text-light move-up"
              href="{{ back_url|default:'/home/administrar/ingresos' }}"><i class="fa fa-arrow-left float-left pt-1"></i> Volver al inicio</a>
          </div>
      {% endif %}
      
          
    </div>
  </div>
</div>
{% endblock body_block %}

templates/administrador/read/pagos_read.html
{% extends "layouts/admin-layout.html" %}

{% load static %}
{% load i18n %}

{% block title_page %}
  Esparta Suites - Administración
{% endblock title_page %}

{% block modulo_label %}
  <span class="">Ver Pago</span>
{% endblock modulo_label %}

{% block opc_panel_class %}
  class="col-lg-3 end-padding-left"
{% endblock opc_panel_class %}

{% block body_block %}
<div class="col-lg-12 mb-5 mb-lg-0 end-padding-right end-padding-left">
  <div class="container rounded modulo border-secondary pb-2">
    <div class="container pt-3 pb-1">
      <div class="divider"></div>

      {% if movimiento %}
        <div class="row pt-3">
          <p class="normal-font text-dark col-sm-6"><strong>Concepto:</strong> <span>{{ movimiento.concepto_movimiento }}</span></p>
          <p class="normal-font text-dark col-sm-6"><strong>Descripción:</strong> <span>{{ movimiento.descripcion_movimiento }}</span></p>
        </div>
        <div class="row pt-3">
          <p class="normal-font text-dark col-sm-6"><strong>Fecha del pago:</strong> <span>{{ movimiento.fecha_movimiento|date:"l, d/m/Y" }}</span></p>
          <p class="normal-font text-dark col-sm-6"><strong>Monto:</strong> <span class="text-success">{{ movimiento.monto_movimiento }}</span></p>
        </div>
        <div class="row pt-3">
          <p class="normal-font text-dark col-sm-6"><strong>Banco receptor:</strong> <span>{{ movimiento.id_banco.nombre_banco }}</span></p>
          <p class="normal-font text-dark col-sm-6"><strong>Banco emisor:</strong> <span>{{ movimiento.banco_emisor }}</span></p>
        </div>
        <div class="row pt-3">
          <p class="normal-font text-dark col-sm-6"><strong>Referencia:</strong> <span>{{ movimiento.referencia_movimiento }}</span></p>
          <p class="normal-font text-dark col-sm-6"><strong>Moneda:</strong> <span>{{ movimiento.tipo_moneda }}</span></p>
        </div>
        <div class="row pt-3">
          <p class="normal-font text-dark col-sm-6"><strong>Estado:</strong>
            {% if movimiento.estado_movimiento == 0 %}
              <span class="text-success">Aprobado</span>
            {% elif movimiento.estado_movimiento == 1 %}
              <span class="text-warning">Rechazado</span>
            {% else %}
              <span>Pendiente</span>
            {% endif %}
          </p>
          <p class="normal-font text-dark col-sm-6"><strong>Fecha de registro:</strong> <span>{{ movimiento.created_at|date:"l, d/m/Y" }}</span></p>
        </div>

        {% if propietario %}
          <div class="row pt-3">
            <p class="normal-font text-dark col-sm-12"><strong>Propietario:</strong> <span>{{ propietario.nombre_propietario }}</span></p>
          </div>
        {% endif %}

        {% if datos_mov %}
          <div class="row pt-3">
            <p class="normal-font text-dark col-sm-6"><strong>Nombre del titular:</strong> <span>{{ datos_mov.nombre_titular }}</span></p>
            <p class="normal-font text-dark col-sm-6"><strong>Correo del titular:</strong> <span>{{ datos_mov.correo_titular }}</span></p>
          </div>
          <div class="row pt-3">
            <p class="normal-font text-dark col-sm-6"><strong>Teléfono:</strong> <span>{{ datos_mov.codigo_area }} {{ datos_mov.telefono_titular }}</span></p>
            <p class="normal-font text-dark col-sm-6"><strong>Tipo transacción:</strong> <span>{{ datos_mov.tipo_transaccion }}</span></p>
          </div>
        {% endif %}

        {% if ingreso and ingreso.imagen_referencial %}
          <div class="row center-area">
            <form method="POST" class="center-area" action="{% url 'condominio_app:downloadReferenciaingreso' %}">
              {% csrf_token %}
              <input type="text" value="{{ ingreso.id_ingreso }}" name="id_ingreso" hidden="hidden">
              <input type="text" value="{{ ingreso.imagen_referencial }}" name="ruta_imagen" hidden="hidden">
              <button type="submit" style="font-size: 13px;" class="btn center-area btn-info mx-auto move-up">
                <strong>Descargar referencia</strong>
              </button>
            </form>
          </div>
        {% else %}
          <div class="row pt-1">
            <p class="normal-font text-center text-dark col-sm-12 text-center"><strong>No se subió imagen de referencia</strong></p>
          </div>
        {% endif %}

        <div class="dropdown-divider"></div>
        <div class="d-grid pt-3" style="justify-content: right;">
          <a class="btn btn-danger btn-cancel col-sm-12 border text-light move-up"
             href="{{ back_url|default:'/home/administrar/validacion-pagos/' }}"><i class="fa fa-arrow-left float-left pt-1"></i> Volver al inicio</a>
        </div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock body_block %}